### ISSUE TITLE
add note that this library is not currently working?

### ISSUE THREAD

**Issue by chrisdrackett** [Noitidart/valtio-persist#9]
As far as I can tell this library is no longer working with updated versions of Valtio. It would be nice to add a note to the readme or similar so people don't waste time debugging. For me this was extra frustrating as I don't get any errors and it just fails completely silently after I updated Valtio.

**Comment by Noitidart** [comment]
Very sorry, that's correct. Upgrading to v1.7 of Valtio breaks it. I'll add that tonight. Sorry about that.

**Comment by chrisdrackett** [comment]
no worries! I know what its like :) It took me a long time to debug because its just been working for months, then stopped without any errors!

**Comment by Noitidart** [comment]
Aw man so sorry about that. Really appreciate you hanging in there. I really need to update this library to use this approach here - https://github.com/Noitidart/valtio-persist/issues/7#issuecomment-1362076372
